services:
  # PostgreSQL avec PostGIS
  postgres:
    build: .
    image: postgis/postgis:17-3.5
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/arrested.json:/docker-entrypoint-initdb.d/arrested.json
      - ./data/bikes-nyc.json:/docker-entrypoint-initdb.d/bikes-nyc.json
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  # Adminer
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: