services:
  # PostgreSQL avec PostGIS
  postgres:
    build: .
    image: postgis/postgis:17-3.5
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: geodb
    volumes:
      - ./data/arrested.json:/docker-entrypoint-initdb.d/arrested.json
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  # PostgreSQL Exporter
  postgres_exporter:
    image: wrouesnel/postgres_exporter:latest
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://admin:adminpassword@postgres:5432/geodb?sslmode=disable
    ports:
      - "9187:9187"  # Port d'écoute de l'exporter
    networks:
      - backend_network

  # Prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./data/prometheus.yml:/etc/prometheus.yml  # Point vers le fichier de configuration
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"  # Port d'accès à l'interface de Prometheus
    networks:
      - backend_network

  # Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"  # Mot de passe admin de Grafana
    ports:
      - "3001:3000"  # Port d'accès à l'interface de Grafana
    depends_on:
      - prometheus
    networks:
      - backend_network

  # Adminer
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080" # Adminer sera accessible sur http://localhost:8080
    depends_on:
      - postgres
    networks:
      - backend_network

  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  prometheus_data: